/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package howispentmoney;

import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tang-pc
 */
public class Activity extends javax.swing.JPanel {

    /**
     * Creates new form Activity
     */
    public Activity() {
            Calendar calendar = Calendar.getInstance();
            initComponents();
            show_user(calendar.get(Calendar.MONTH)+1);
            System.out.println(Login.username_tf.getText());
    }
    public static ArrayList<Userdata> userData(int numOfMonth){
        Connection connect = null;
        Statement s = null;
        String userid = null;
        ArrayList<Userdata> userData = new ArrayList<>();
        try{
            connect = DriverManager.getConnection("jdbc:derby:C:\\Users\\Thitiwut\\Documents\\GitHub\\HowISpentMoney\\.derby\\db_hism", "", "");
            String sql = "SELECT USERNAME, DATE(TIMESTAMP) AS TIME, MONTH(TIMESTAMP) AS MONTH , TYPE, TYPE_DES, VALUE FROM APP.USERDATA WHERE USERNAME = '"+DatabaseConnection.user_name+"'";
            s = connect.createStatement();
            ResultSet rec = s.executeQuery(sql);
            Userdata theData;

            while(rec.next()){
                if (rec.getInt("MONTH")==numOfMonth){
                    theData = new Userdata(rec.getDate("TIME"), rec.getString("TYPE"), rec.getString("TYPE_DES"), rec.getDouble("VALUE"));
                    userData.add(theData);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        return userData;
    }
    public void show_user(int m){
        ArrayList<Userdata> list = userData(m);
        DefaultTableModel model = (DefaultTableModel)jTable_Display.getModel();   
        model.setRowCount(0);
        Object[] row = new Object[4];
        for (int i=0; i<list.size(); i++){
            row[0] = list.get(i).getTIMESTAMP();
            if (list.get(i).getTYPE().equals("In")){
                row[1] = "Income";
            }else{
                row[1] = "Expend";
            }
            row[2] = list.get(i).getTYPE_DES();
            row[3] = list.get(i).getVALUE();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jTable_Display.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Display.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable_Display.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Type", "Type Des", "Value"
            }
        ));
        jTable_Display.setSelectionBackground(new java.awt.Color(190, 28, 80));
        jScrollPane1.setViewportView(jTable_Display);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 260, 610, 268);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(90, 220, 104, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(DatabaseConnection.user_name);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 310, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View All Activity");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 150, 30);

        jButton1.setBackground(new java.awt.Color(31, 34, 41));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back to DashBoard");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 560, 800, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/vabg.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.demo.toDash();
        System.out.println("In");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String check_month_activity = (String)jComboBox1.getSelectedItem();
        int monthToInt;
        switch (check_month_activity){
            case "January":
                show_user(1);
                break;
            case "Febuary":
                show_user(2);
                break;
            case "March":
                show_user(3);
                break;
            case "Aprill":
                show_user(4);
                break;
            case "May":
                show_user(5);
                break;
            case "June":
                show_user(6);
                break;
            case "July":
                show_user(7);
                break;
            case "August":
                show_user(8);
                break;
            case "September":
                show_user(9);
                break;
            case "October":
                show_user(10);
                break;
            case "November":
                show_user(11);
                break;
            case "December":
                show_user(12);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display;
    // End of variables declaration//GEN-END:variables
}
