/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package howispentmoney;

import static howispentmoney.Main.main_frame;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author tang-pc
 */
public class Dashboard extends javax.swing.JPanel {
    /**
     * Creates new form Dashboard
     */
    Calendar calendar = Calendar.getInstance();
    double income_total, expend_total;
    public Dashboard() {
        showValue();
        initComponents();
        
        
    }
    public void showValue(){
        
        ArrayList<Userdata> list = Activity.userData(calendar.get(Calendar.MONTH)+1);      
        for (int i=0; i<list.size(); i++){
            switch (list.get(i).getTYPE_DES()) {
                case "Income":
                    income_total += list.get(i).getVALUE();
                    System.out.println(list.get(i).getVALUE());
                    break;
                default:
                    expend_total += list.get(i).getVALUE();
                    break;
            }
        }
    }
    public JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_chart1 = new javax.swing.JButton();
        btn_chart2 = new javax.swing.JButton();
        activitybutton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        income_tf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        expend_tf = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lb_income = new javax.swing.JLabel();
        lb_expend = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(31, 34, 41));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(31, 34, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(DatabaseConnection.user_name);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setText(calendar.get(Calendar.YEAR)+"");

        month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setText(DatabaseConnection.getMonth());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(year)
                    .addComponent(month))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(year)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(20, 30, 232, 189);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_chart1.setBackground(new java.awt.Color(190, 28, 80));
        btn_chart1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_chart1.setForeground(new java.awt.Color(255, 255, 255));
        btn_chart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/pie-chart.png"))); // NOI18N
        btn_chart1.setText("Visualise All");
        btn_chart1.setBorderPainted(false);
        btn_chart1.setIconTextGap(10);
        btn_chart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chart1ActionPerformed(evt);
            }
        });

        btn_chart2.setBackground(new java.awt.Color(190, 28, 80));
        btn_chart2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_chart2.setForeground(new java.awt.Color(255, 255, 255));
        btn_chart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/pie-chart.png"))); // NOI18N
        btn_chart2.setText("Visualise Unnes");
        btn_chart2.setBorderPainted(false);
        btn_chart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chart2ActionPerformed(evt);
            }
        });

        activitybutton.setBackground(new java.awt.Color(190, 28, 80));
        activitybutton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        activitybutton.setForeground(new java.awt.Color(255, 255, 255));
        activitybutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/statement.png"))); // NOI18N
        activitybutton.setText("View Activity");
        activitybutton.setBorderPainted(false);
        activitybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitybuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(activitybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activitybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3);
        jPanel3.setBounds(170, 500, 500, 220);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        income_tf.setBackground(new java.awt.Color(255, 255, 255));
        income_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        income_tf.setForeground(new java.awt.Color(0, 0, 0));
        income_tf.setBorder(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/ok.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        expend_tf.setBackground(new java.awt.Color(255, 255, 255));
        expend_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        expend_tf.setForeground(new java.awt.Color(0, 0, 0));
        expend_tf.setBorder(null);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Travel", "Clothes", "Gadget", "Utility", "Other", "Unnecesary"}));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INCOME TODAY");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("EXPEND TODAY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(expend_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(income_tf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2))))
                .addGap(178, 178, 178))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(income_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(expend_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jPanel5.add(jPanel4);
        jPanel4.setBounds(160, 300, 510, 200);

        lb_income.setForeground(new java.awt.Color(156, 161, 167));
        lb_income.setText("฿ "+income_total);
        jPanel5.add(lb_income);
        lb_income.setBounds(680, 100, 73, 16);

        lb_expend.setForeground(new java.awt.Color(156, 161, 167));
        lb_expend.setText("฿ "+expend_total);
        jPanel5.add(lb_expend);
        lb_expend.setBounds(680, 150, 73, 16);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/howispentmoney/dbbg.jpg"))); // NOI18N
        jPanel5.add(bg);
        bg.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

        
    private void activitybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitybuttonActionPerformed
        Main.demo.addActPage();
        Main.demo.toAct();
        
    }//GEN-LAST:event_activitybuttonActionPerformed

    private void btn_chart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chart1ActionPerformed
        // TODO add your handling code here:
            Main.demo.addChartPage();
            Main.demo.toChart();
    }//GEN-LAST:event_btn_chart1ActionPerformed

    private void btn_chart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chart2ActionPerformed
        // TODO add your handling code here:
        Main.demo.addChartPage();
        Main.demo.toChart2();
    }//GEN-LAST:event_btn_chart2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String value = (String)jComboBox1.getSelectedItem();
        Double income = Double.parseDouble(income_tf.getText());
        Double expend = Double.parseDouble(expend_tf.getText());
        DatabaseConnection.insert_data(value, income, expend);
        income_total += income;
        expend_total += expend;
        Main.demo.refreshDash();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activitybutton;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_chart1;
    private javax.swing.JButton btn_chart2;
    private javax.swing.JTextField expend_tf;
    private javax.swing.JTextField income_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_expend;
    private javax.swing.JLabel lb_income;
    private javax.swing.JLabel month;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
