/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package howispentmoney;

import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author Thitiwut
 */
public class PieChartAll extends javax.swing.JFrame {

    /**
     * Creates new form PieChartAll
     */
    public PieChartAll() {
        initComponents();
        this.add(new ChartPanel(createChart(createDataset())));
    }
    
    private static PieDataset createDataset( ) {
        ArrayList<Userdata> list = Activity.userData();      
        DefaultPieDataset dataset = new DefaultPieDataset( );
        System.out.println("list : " + list.size());
        double income_total=0, food_total=0, travel_total=0, other_total=0, clothes_total=0, utilityBills_total=0, gadget_total=0;
        for (int i=0; i<list.size(); i++){
            switch (list.get(i).getTYPE_DES()) {
                case "Income":
                    income_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), income_total);
                    break;
                case "Clothes":
                    clothes_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), clothes_total);
                    break;
                case "Travel":
                    travel_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), travel_total);
                    break;
                case "Other":
                    other_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), other_total);
                    break;
                case "Food":
                    food_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), food_total);
                    break;
                case "utility":
                    utilityBills_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), utilityBills_total);
                    break;
                case "Gadget":
                    gadget_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), gadget_total);
                    break;
                default:
                    break;
            }
        } 
        return dataset;         
   }
    
    private static JFreeChart createChart( PieDataset dataset ) {
        JFreeChart chart = ChartFactory.createPieChart(      
            "Pie Chart",   // chart title 
            dataset,          // data    
            true,             // include legend   
            true, 
            false);

        return chart;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PieChartAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PieChartAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PieChartAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PieChartAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PieChartAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
