/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package howispentmoney;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JButton;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author Thitiwut
 */
public class PieChartDetail extends javax.swing.JPanel {
    /**
     * Creates new form PieChartDetail
     */
    public PieChartDetail() {
        initComponents();
        this.add(new ChartPanel(createChart(createDataset())), BorderLayout.CENTER);
    }

    private static PieDataset createDataset( ) {
        Calendar calendar = Calendar.getInstance();        
        ArrayList<Userdata> list = Activity.userData(calendar.get(Calendar.MONTH)+1);      
        DefaultPieDataset dataset = new DefaultPieDataset( );
        System.out.println("list : " + list.size());
        double income_total=0, food_total=0, travel_total=0, other_total=0, clothes_total=0, utilityBills_total=0, gadget_total=0, Unnecessary_total=0;
        for (int i=0; i<list.size(); i++){
            switch (list.get(i).getTYPE_DES()) {
                case "Income":
                    income_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), income_total);
                    break;
                case "Clothes":
                    clothes_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), clothes_total);
                    break;
                case "Travel":
                    travel_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), travel_total);
                    break;
                case "Other":
                    other_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), other_total);
                    break;
                case "Food":
                    food_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), food_total);
                    break;
                case "utility":
                    utilityBills_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), utilityBills_total);
                    break;
                case "Unnecesary":
                    Unnecessary_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), Unnecessary_total);
                    break;
                case "Gadget":
                    gadget_total += list.get(i).getVALUE();
                    dataset.setValue(list.get(i).getTYPE_DES(), gadget_total);
                    break;
                default:
                    break;
            }
        } 
        return dataset;         
   }
    
    private static JFreeChart createChart( PieDataset dataset ) {
        JFreeChart chart = ChartFactory.createPieChart(      
            "Pie Chart ",   // chart title 
            dataset,          // data    
            true,             // include legend   
            true, 
            false);

        return chart;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.demo.toDash();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
